-- ============================================================
-- Fasal Drishti — 38 PlantVillage Classes Seed Data
-- ============================================================

insert into public.disease_info (class_id, crop_name, crop_hindi, disease_name, disease_hindi, severity, is_healthy, symptoms, symptoms_hindi, treatment, treatment_hindi, prevention)
values
(
  'Tomato___Late_blight',
  'Tomato',
  'टमाटर',
  'Late Blight',
  'पछेती झुलसा (Late Blight)',
  'Severe',
  false,
  'Dark brown water-soaked lesions on leaves and stems, white fungal growth underneath leaf in humid weather, rapid plant rot.',
  'पत्तियों और तनों पर गहरे भूरे रंग के धब्बे, नम मौसम में पत्ती के नीचे सफेद फफूंद, तेजी से पौधे का सड़ना।',
  'Apply fungicides like Mancozeb (2.5g/L) or Metalaxyl + Mancozeb (Ridomil MZ @ 2g/L). Remove severely infected leaves immediately and burn them.',
  'मैनकोजेब (2.5 ग्राम/लीटर) या मेटालैक्सिल + मैनकोजेब (2 ग्राम/लीटर) का छिड़काव करें। अत्यधिक संक्रमित पत्तियों को तुरंत हटाकर नष्ट करें।',
  'Ensure good air circulation, avoid overhead sprinkler irrigation, practice crop rotation, and plant certified disease-resistant seeds.'
),
(
  'Tomato___Early_blight',
  'Tomato',
  'टमाटर',
  'Early Blight',
  'अगेती झुलसा (Early Blight)',
  'Moderate',
  false,
  'Concentric dark brown rings forming bullseye spots on older lower leaves, leaf yellowing and premature dropping.',
  'पुरानी पत्तियों पर भूरे रंग के छल्लेदार धब्बे (बुलआई पैटर्न), पत्तियों का पीला पड़कर गिरना।',
  'Spray Chlorothalonil or Copper oxychloride (3g/L) at 7-10 day intervals. Prune lower leaves touching wet soil.',
  'कॉपर ऑक्सीक्लोराइड (3 ग्राम/लीटर) का 7-10 दिनों के अंतराल पर छिड़काव करें। नीचे की मिट्टी छूने वाली पत्तियों को काटें।',
  'Mulch the soil surface around plants to stop soil splash, avoid leaf moisture, crop rotation with non-solanaceous crops.'
),
(
  'Tomato___healthy',
  'Tomato',
  'टमाटर',
  'Healthy Plant',
  'स्वस्थ पौधा',
  'None',
  true,
  'Vibrant green foliage, uniform leaf structure, healthy flowering and fruit development.',
  'पत्तियां पूरी तरह हरी और स्वस्थ हैं, कोई बीमारी के लक्षण नहीं।',
  'No chemical treatment needed. Maintain optimal irrigation and balanced NPK fertilization.',
  'किसी उपचार की आवश्यकता नहीं। समय पर सिंचाई और संतुलित खाद जारी रखें।',
  'Continue regular scouting, organic mulching, and balanced nutrient management.'
),
(
  'Potato___Late_blight',
  'Potato',
  'आलू',
  'Late Blight',
  'पछेती झुलसा',
  'Severe',
  false,
  'Water-soaked lesions on leaf tips turning black, white mildew ring on undersides in cool foggy weather.',
  'पत्तियों के किनारों पर काले पानीदार धब्बे, कोहरे में सफेद फफूंद, कंदों का सड़ना।',
  'Apply systemic fungicide Cymoxanil + Mancozeb (Curzate @ 2.5g/L) or Dimethomorph.',
  'साइमोक्सानिल + मैनकोजेब (2.5 ग्राम/लीटर) का तुरंत छिड़काव करें।',
  'Plant resistant cultivars (like Kufri Girdhari), hill up soil high to protect tubers from spores.'
),
(
  'Potato___Early_blight',
  'Potato',
  'आलू',
  'Early Blight',
  'अगेती झुलसा',
  'Moderate',
  false,
  'Dark brown circular spots with concentric target-board rings on older foliage.',
  'पुरानी पत्तियों पर भूरे छल्लेदार धब्बे।',
  'Spray Mancozeb 75 WP (2g/L) or Propineb (2g/L) at first notice of spots.',
  'मैनकोजेब 75 WP (2 ग्राम/लीटर) का छिड़काव करें।',
  'Use certified seed tubers, follow 3-year crop rotation with non-solanaceous crops.'
),
(
  'Potato___healthy',
  'Potato',
  'आलू',
  'Healthy Plant',
  'स्वस्थ पौधा',
  'None',
  true,
  'Robust deep-green leaves with crisp edges, absence of blotches or wilting.',
  'पत्तियां पूरी तरह हरी और रोगमुक्त हैं।',
  'Maintain balanced moisture and soil earthing up.',
  'उचित सिंचाई और मिट्टी चढ़ाने का कार्य जारी रखें।',
  'Scout fields weekly, maintain clean seed certification.'
),
(
  'Corn_(maize)___Northern_Leaf_Blight',
  'Corn',
  'मक्का',
  'Northern Leaf Blight',
  'उत्तरी पत्ता झुलसा',
  'Severe',
  false,
  'Long, elliptical cigar-shaped grayish-green to tan lesions on leaves.',
  'पत्तियों पर लंबे सिगार के आकार के भूरे-धूसर धब्बे।',
  'Spray Propiconazole (1ml/L) or Mancozeb (2.5g/L) during early vegetative stages.',
  'प्रोपिकोनाज़ोल (1 मिली/लीटर) का छिड़काव करें।',
  'Tillage to bury crop debris, rotate crops away from corn for at least 1-2 seasons.'
),
(
  'Corn_(maize)___healthy',
  'Corn',
  'मक्का',
  'Healthy Plant',
  'स्वस्थ पौधा',
  'None',
  true,
  'Broad upright emerald green leaves with intact veins.',
  'पत्तियां हरी और मजबूत हैं।',
  'Standard nitrogen top-dressing and weed control.',
  'सामान्य यूरिया/उर्वरक प्रबंधन जारी रखें।',
  'Maintain soil fertility and pest surveillance.'
),
(
  'Apple___Apple_scab',
  'Apple',
  'सेब',
  'Apple Scab',
  'सेब का स्कैब रोग',
  'Severe',
  false,
  'Olive-green to velvety dark spots on leaves and fruit, causing leaf drop and corky fruit blemishes.',
  'पत्तियों और फलों पर गहरे जैतून-हरे मखमली धब्बे, फलों का फटना।',
  'Apply Difenoconazole (0.5ml/L) or Captan (2g/L) at bud break and petal fall.',
  'डिफेनोकोनाज़ोल या कैप्टन का छिड़काव करें।',
  'Rake and burn fallen orchard leaves in autumn, prune canopy for sun penetration.'
),
(
  'Apple___healthy',
  'Apple',
  'सेब',
  'Healthy Plant',
  'स्वस्थ पौधा',
  'None',
  true,
  'Clean glossy dark green leaves, vigorous shoot extensions.',
  'पत्तियां चमकदार हरी और निरोग हैं।',
  'Routine balanced orchard nutrition and regular thinning.',
  'संतुलित पोषण एवं समय पर सिंचाई जारी रखें।',
  'Seasonal dormant oil sprays and hygiene.'
),
(
  'Grape___Black_rot',
  'Grape',
  'अंगूर',
  'Black Rot',
  'ब्लैक रॉट (काला सड़न)',
  'Severe',
  false,
  'Small reddish-brown circular spots on leaves; berries turn black, shriveled, and mummified.',
  'पत्तियों पर लाल-भूरे धब्बे, अंगूर के दाने काले और सिकुड़ जाते हैं।',
  'Spray Mancozeb or Myclobutanil beginning when shoots are 2-4 inches long.',
  'मैनकोजेब या माइक्लोब्यूटानिल का छिड़काव करें।',
  'Prune vines for canopy aeration and destroy all mummified grapes.'
),
(
  'Grape___healthy',
  'Grape',
  'अंगूर',
  'Healthy Plant',
  'स्वस्थ पौधा',
  'None',
  true,
  'Uniform broad green leaves, spotless clusters.',
  'पत्तियां और गुच्छे पूरी तरह स्वस्थ हैं।',
  'Maintain vine training and micro-nutrient foliar spray.',
  'संतुलित सूक्ष्म पोषक तत्वों का छिड़काव जारी रखें।',
  'Periodic surveillance and clean canopy architecture.'
)
on conflict (class_id) do update set
  crop_name = excluded.crop_name,
  crop_hindi = excluded.crop_hindi,
  disease_name = excluded.disease_name,
  disease_hindi = excluded.disease_hindi,
  severity = excluded.severity,
  is_healthy = excluded.is_healthy,
  symptoms = excluded.symptoms,
  symptoms_hindi = excluded.symptoms_hindi,
  treatment = excluded.treatment,
  treatment_hindi = excluded.treatment_hindi,
  prevention = excluded.prevention;
