"""
Disease Knowledge Base for all 38 PlantVillage Classes.
Provides English & Hindi names, symptoms, treatments, prevention, and severity.
"""

from typing import Dict, Any, List

CLASS_NAMES: List[str] = [
    "Apple___Apple_scab",
    "Apple___Black_rot",
    "Apple___Cedar_apple_rust",
    "Apple___healthy",
    "Blueberry___healthy",
    "Cherry_(including_sour)___Powdery_mildew",
    "Cherry_(including_sour)___healthy",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
    "Corn_(maize)___Common_rust_",
    "Corn_(maize)___Northern_Leaf_Blight",
    "Corn_(maize)___healthy",
    "Grape___Black_rot",
    "Grape___Esca_(Black_Measles)",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    "Grape___healthy",
    "Orange___Haunglongbing_(Citrus_greening)",
    "Peach___Bacterial_spot",
    "Peach___healthy",
    "Pepper,_bell___Bacterial_spot",
    "Pepper,_bell___healthy",
    "Potato___Early_blight",
    "Potato___Late_blight",
    "Potato___healthy",
    "Raspberry___healthy",
    "Soybean___healthy",
    "Squash___Powdery_mildew",
    "Strawberry___Leaf_scorch",
    "Strawberry___healthy",
    "Tomato___Bacterial_spot",
    "Tomato___Early_blight",
    "Tomato___Late_blight",
    "Tomato___Leaf_Mold",
    "Tomato___Septoria_leaf_spot",
    "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato___Tomato_mosaic_virus",
    "Tomato___healthy"
]

DISEASE_METADATA: Dict[str, Dict[str, Any]] = {
    "Tomato___Late_blight": {
        "crop_name": "Tomato",
        "crop_hindi": "टमाटर",
        "disease_name": "Late Blight",
        "disease_hindi": "पछेती झुलसा (Late Blight)",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "Dark brown water-soaked lesions on leaves and stems, white fungal growth underneath leaf in humid weather, rapid plant rot.",
        "symptoms_hindi": "पत्तियों और तनों पर गहरे भूरे रंग के धब्बे, नम मौसम में पत्ती के नीचे सफेद फफूंद, तेजी से पौधे का सड़ना।",
        "treatment": "Apply fungicides like Mancozeb (2.5g/L) or Metalaxyl + Mancozeb (Ridomil MZ @ 2g/L). Remove severely infected leaves immediately and burn them.",
        "treatment_hindi": "मैनकोजेब (2.5 ग्राम/लीटर) या मेटालैक्सिल + मैनकोजेब (2 ग्राम/लीटर) का छिड़काव करें। अत्यधिक संक्रमित पत्तियों को तुरंत हटाकर नष्ट करें।",
        "prevention": "Ensure good air circulation, avoid overhead sprinkler irrigation, practice crop rotation, and plant certified disease-resistant seeds."
    },
    "Tomato___Early_blight": {
        "crop_name": "Tomato",
        "crop_hindi": "टमाटर",
        "disease_name": "Early Blight",
        "disease_hindi": "अगेती झुलसा (Early Blight)",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Concentric dark brown rings forming 'bullseye' spots on older lower leaves, leaf yellowing and premature dropping.",
        "symptoms_hindi": "पुरानी पत्तियों पर भूरे रंग के छल्लेदार धब्बे (बुलआई पैटर्न), पत्तियों का पीला पड़कर गिरना।",
        "treatment": "Spray Chlorothalonil or Copper oxychloride (3g/L) at 7-10 day intervals. Prune lower leaves touching wet soil.",
        "treatment_hindi": "कॉपर ऑक्सीक्लोराइड (3 ग्राम/लीटर) का 7-10 दिनों के अंतराल पर छिड़काव करें। नीचे की मिट्टी छूने वाली पत्तियों को काटें।",
        "prevention": "Mulch the soil surface around plants to stop soil splash, avoid leaf moisture, crop rotation with non-solanaceous crops."
    },
    "Tomato___Bacterial_spot": {
        "crop_name": "Tomato",
        "crop_hindi": "टमाटर",
        "disease_name": "Bacterial Spot",
        "disease_hindi": "जीवाणु धब्बा रोग",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Small, dark greasy spots with yellow halos on leaves, leaves may turn brown and drop.",
        "symptoms_hindi": "पत्तियों पर छोटे, काले तैलीय धब्बे जिनके चारों ओर पीला घेरा होता है।",
        "treatment": "Apply Copper Hydroxide mixed with Streptocycline (0.5g/10L) to reduce bacterial spread.",
        "treatment_hindi": "कॉपर हाइड्रॉक्साइड के साथ स्ट्रेप्टोसाइक्लिन (0.5 ग्राम / 10 लीटर) का छिड़काव करें।",
        "prevention": "Use certified disease-free seeds, avoid sprinkler irrigation, sanitize farm tools."
    },
    "Tomato___Leaf_Mold": {
        "crop_name": "Tomato",
        "crop_hindi": "टमाटर",
        "disease_name": "Leaf Mold",
        "disease_hindi": "पत्ती फफूंद",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Pale greenish-yellow spots on upper leaf surfaces, olive-green velvety mold on the underside.",
        "symptoms_hindi": "पत्ती की ऊपरी सतह पर हल्के हरे-पीले धब्बे और निचली सतह पर जैतून-हरे रंग की फफूंद।",
        "treatment": "Spray Copper-based fungicides or Azoxystrobin. Increase greenhouse ventilation.",
        "treatment_hindi": "कॉपर फफूंदनाशक का छिड़काव करें और खेत/पॉलीहाउस में हवा का संचार बढ़ाएं।",
        "prevention": "Keep foliage dry, prune dense branches to allow sunlight and airflow."
    },
    "Tomato___Septoria_leaf_spot": {
        "crop_name": "Tomato",
        "crop_hindi": "टमाटर",
        "disease_name": "Septoria Leaf Spot",
        "disease_hindi": "सेप्टोरिया पत्ती धब्बा",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Circular spots with dark brown margins and gray centers containing tiny black specks.",
        "symptoms_hindi": "गहरे भूरे किनारों और भूरे केंद्रों वाले गोल धब्बे जिनमें छोटे काले दाने होते हैं।",
        "treatment": "Apply Mancozeb or Chlorothalonil every 7-14 days during wet conditions.",
        "treatment_hindi": "गीले मौसम में हर 7-14 दिनों में मैनकोजेब का छिड़काव करें।",
        "prevention": "Stake plants upright, remove bottom foliage, and rotate crops."
    },
    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "crop_name": "Tomato",
        "crop_hindi": "टमाटर",
        "disease_name": "Two-Spotted Spider Mite",
        "disease_hindi": "लाल मकड़ी कीट (स्पाइडर माइट)",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "Fine yellow stippling on leaf surface, fine webbing under leaves, leaves bronzing and drying up.",
        "symptoms_hindi": "पत्तियों पर बारीक पीले बिंदु, पत्ती के नीचे जाले, पत्तियों का सूखना।",
        "treatment": "Spray Neem oil (5ml/L) or acaricides such as Spiromesifen (Oberon @ 1ml/L) or Abamectin.",
        "treatment_hindi": "नीम का तेल (5 मिली/लीटर) या स्पाइरोमेसिफेन (1 मिली/लीटर) का पत्तियों के नीचे छिड़काव करें।",
        "prevention": "Keep plants well watered, avoid dusty field conditions, encourage beneficial predatory insects."
    },
    "Tomato___Target_Spot": {
        "crop_name": "Tomato",
        "crop_hindi": "टमाटर",
        "disease_name": "Target Spot",
        "disease_hindi": "टारगेट स्पॉट",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Brown circular lesions with concentric rings on leaves, flowers, and fruit.",
        "symptoms_hindi": "पत्तियों और फलों पर गोल भूरे छल्लेदार धब्बे।",
        "treatment": "Apply fungicides like Chlorothalonil or Pyraclostrobin.",
        "treatment_hindi": "क्लोरोथैलोनिल फफूंदनाशक का छिड़काव करें।",
        "prevention": "Ensure adequate plant spacing, avoid excessive nitrogen fertilization."
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "crop_name": "Tomato",
        "crop_hindi": "टमाटर",
        "disease_name": "Yellow Leaf Curl Virus",
        "disease_hindi": "पीला पत्ता मरोड़ वायरस (लीफ कर्ल)",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "Upward curling and cupping of leaves, strong yellow margins, severe stunting and aborted fruit set.",
        "symptoms_hindi": "पत्तियों का ऊपर की ओर मुड़ना, पत्तों का पीला पड़ना, पौधे का बौना रह जाना।",
        "treatment": "Control whitefly vectors using Imidacloprid (0.5ml/L) or Acetamiprid. Remove infected plants immediately.",
        "treatment_hindi": "सफेद मक्खी की रोकथाम हेतु इमिडाक्लोप्रिड (0.5 मिली/लीटर) छिड़कें। रोगग्रस्त पौधों को उखाड़कर नष्ट करें।",
        "prevention": "Install yellow sticky traps, use insect netting, and cultivate TYLCV-resistant varieties."
    },
    "Tomato___Tomato_mosaic_virus": {
        "crop_name": "Tomato",
        "crop_hindi": "टमाटर",
        "disease_name": "Mosaic Virus",
        "disease_hindi": "मोज़ेक वायरस",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "Mottled light and dark green patterns on leaves, fern-like distorted leaf growth, internal browning in fruits.",
        "symptoms_hindi": "पत्तियों पर हल्का व गहरा हरा मोज़ेक धब्बेदार पैटर्न, पत्तियों का सिकुड़ना।",
        "treatment": "No chemical cure. Uproot and burn infected plants. Disinfect hands and shears with 10% TSP.",
        "treatment_hindi": "कोई रासायनिक इलाज नहीं। प्रभावित पौधों को तुरंत उखाड़कर नष्ट करें और औजारों को साफ रखें।",
        "prevention": "Control insect vectors, wash hands before handling crops, use virus-resistant seeds."
    },
    "Tomato___healthy": {
        "crop_name": "Tomato",
        "crop_hindi": "टमाटर",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Vibrant green foliage, uniform leaf structure, healthy flowering and fruit development.",
        "symptoms_hindi": "पत्तियां पूरी तरह हरी और स्वस्थ हैं, कोई बीमारी के लक्षण नहीं।",
        "treatment": "No chemical treatment needed. Maintain optimal irrigation and balanced NPK fertilization.",
        "treatment_hindi": "किसी उपचार की आवश्यकता नहीं। समय पर सिंचाई और संतुलित खाद जारी रखें।",
        "prevention": "Continue regular scouting, organic mulching, and balanced nutrient management."
    },
    "Potato___Early_blight": {
        "crop_name": "Potato",
        "crop_hindi": "आलू",
        "disease_name": "Early Blight",
        "disease_hindi": "अगेती झुलसा",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Dark brown circular spots with concentric target-board rings on older foliage.",
        "symptoms_hindi": "पुरानी पत्तियों पर भूरे छल्लेदार धब्बे।",
        "treatment": "Spray Mancozeb 75 WP (2g/L) or Propineb (2g/L) at first notice of spots.",
        "treatment_hindi": "मैनकोजेब 75 WP (2 ग्राम/लीटर) का छिड़काव करें।",
        "prevention": "Use certified seed tubers, follow 3-year crop rotation with non-solanaceous crops."
    },
    "Potato___Late_blight": {
        "crop_name": "Potato",
        "crop_hindi": "आलू",
        "disease_name": "Late Blight",
        "disease_hindi": "पछेती झुलसा",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "Water-soaked lesions on leaf tips turning black, white mildew ring on undersides in cool foggy weather.",
        "symptoms_hindi": "पत्तियों के किनारों पर काले पानीदार धब्बे, कोहरे में सफेद फफूंद, कंदों का सड़ना।",
        "treatment": "Apply systemic fungicide Cymoxanil + Mancozeb (Curzate @ 2.5g/L) or Dimethomorph.",
        "treatment_hindi": "साइमोक्सानिल + मैनकोजेब (2.5 ग्राम/लीटर) का तुरंत छिड़काव करें।",
        "prevention": "Plant resistant cultivars (like Kufri Girdhari), hill up soil high to protect tubers from spores."
    },
    "Potato___healthy": {
        "crop_name": "Potato",
        "crop_hindi": "आलू",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Robust deep-green leaves with crisp edges, absence of blotches or wilting.",
        "symptoms_hindi": "पत्तियां पूरी तरह हरी और रोगमुक्त हैं।",
        "treatment": "Maintain balanced moisture and soil earthing up.",
        "treatment_hindi": "उचित सिंचाई और मिट्टी चढ़ाने का कार्य जारी रखें।",
        "prevention": "Scout fields weekly, maintain clean seed certification."
    },
    "Corn_(maize)___Common_rust_": {
        "crop_name": "Corn",
        "crop_hindi": "मक्का",
        "disease_name": "Common Rust",
        "disease_hindi": "मक्का रतुआ (गेरुआ)",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Cinnamon-brown powdery pustules scattered over both upper and lower leaf surfaces.",
        "symptoms_hindi": "पत्तियों के दोनों तरफ दालचीनी जैसे भूरे रंग के फफोले।",
        "treatment": "Apply Azoxystrobin + Difenoconazole or Mancozeb if pustules appear before tasseling.",
        "treatment_hindi": "एज़ोक्सीस्ट्रोबिन या मैनकोजेब का छिड़काव करें।",
        "prevention": "Select rust-tolerant hybrid seeds and plant early in season."
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "crop_name": "Corn",
        "crop_hindi": "मक्का",
        "disease_name": "Northern Leaf Blight",
        "disease_hindi": "उत्तरी पत्ता झुलसा",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "Long, elliptical cigar-shaped grayish-green to tan lesions on leaves.",
        "symptoms_hindi": "पत्तियों पर लंबे सिगार के आकार के भूरे-धूसर धब्बे।",
        "treatment": "Spray Propiconazole (1ml/L) or Mancozeb (2.5g/L) during early vegetative stages.",
        "treatment_hindi": "प्रोपिकोनाज़ोल (1 मिली/लीटर) का छिड़काव करें।",
        "prevention": "Tillage to bury crop debris, rotate crops away from corn for at least 1-2 seasons."
    },
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": {
        "crop_name": "Corn",
        "crop_hindi": "मक्का",
        "disease_name": "Gray Leaf Spot",
        "disease_hindi": "ग्रे लीफ स्पॉट",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Rectangular tan to gray lesions bounded sharply by leaf veins.",
        "symptoms_hindi": "पत्तियों की नसों के बीच आयताकार धूसर धब्बे।",
        "treatment": "Foliar fungicide application with Pyraclostrobin or Tebuconazole.",
        "treatment_hindi": "टेबुकोनाज़ोल फफूंदनाशक का छिड़काव करें।",
        "prevention": "Utilize resistant hybrids, crop residue management."
    },
    "Corn_(maize)___healthy": {
        "crop_name": "Corn",
        "crop_hindi": "मक्का",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Broad upright emerald green leaves with intact veins.",
        "symptoms_hindi": "पत्तियां हरी और मजबूत हैं।",
        "treatment": "Standard nitrogen top-dressing and weed control.",
        "treatment_hindi": "सामान्य यूरिया/उर्वरक प्रबंधन जारी रखें।",
        "prevention": "Maintain soil fertility and pest surveillance."
    },
    "Apple___Apple_scab": {
        "crop_name": "Apple",
        "crop_hindi": "सेब",
        "disease_name": "Apple Scab",
        "disease_hindi": "सेब का स्कैब रोग",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "Olive-green to velvety dark spots on leaves and fruit, causing leaf drop and corky fruit blemishes.",
        "symptoms_hindi": "पत्तियों और फलों पर गहरे जैतून-हरे मखमली धब्बे, फलों का फटना।",
        "treatment": "Apply Difenoconazole (0.5ml/L) or Captan (2g/L) at bud break and petal fall.",
        "treatment_hindi": "डिफेनोकोनाज़ोल या कैप्टन का छिड़काव करें।",
        "prevention": "Rake and burn fallen orchard leaves in autumn, prune canopy for sun penetration."
    },
    "Apple___Black_rot": {
        "crop_name": "Apple",
        "crop_hindi": "सेब",
        "disease_name": "Black Rot",
        "disease_hindi": "काला सड़न रोग",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "'Frog-eye' circular spots on leaves, rotting fruit shriveling into black mummies.",
        "symptoms_hindi": "पत्तियों पर मेंढक की आंख जैसे गोल धब्बे, फलों का काला होकर सूखना।",
        "treatment": "Prune out dead wood, cankers, and mummified fruit. Spray Thiophanate-methyl.",
        "treatment_hindi": "सूखी और सड़ी टहनियों को काटकर जलाएं। थायोफिनेट मिथाइल का छिड़काव करें।",
        "prevention": "Wound management on tree branches, sanitation of pruned materials."
    },
    "Apple___Cedar_apple_rust": {
        "crop_name": "Apple",
        "crop_hindi": "सेब",
        "disease_name": "Cedar Apple Rust",
        "disease_hindi": "देवदार सेब रतुआ",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Bright orange-yellow circular spots on upper leaf surfaces, tiny cup structures beneath.",
        "symptoms_hindi": "पत्ती की ऊपरी सतह पर चमकीले नारंगी-पीले धब्बे।",
        "treatment": "Apply Myclobutanil or Mancozeb from tight cluster through petal fall.",
        "treatment_hindi": "माइक्लोब्यूटानिल का छिड़काव करें।",
        "prevention": "Remove nearby wild juniper/cedar host bushes if within 1-2 miles."
    },
    "Apple___healthy": {
        "crop_name": "Apple",
        "crop_hindi": "सेब",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Clean glossy dark green leaves, vigorous shoot extensions.",
        "symptoms_hindi": "पत्तियां चमकदार हरी और निरोग हैं।",
        "treatment": "Routine balanced orchard nutrition and regular thinning.",
        "treatment_hindi": "संतुलित पोषण एवं समय पर सिंचाई जारी रखें।",
        "prevention": "Seasonal dormant oil sprays and hygiene."
    },
    "Grape___Black_rot": {
        "crop_name": "Grape",
        "crop_hindi": "अंगूर",
        "disease_name": "Black Rot",
        "disease_hindi": "ब्लैक रॉट (काला सड़न)",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "Small reddish-brown circular spots on leaves; berries turn black, shriveled, and mummified.",
        "symptoms_hindi": "पत्तियों पर लाल-भूरे धब्बे, अंगूर के दाने काले और सिकुड़ जाते हैं।",
        "treatment": "Spray Mancozeb or Myclobutanil beginning when shoots are 2-4 inches long.",
        "treatment_hindi": "मैनकोजेब या माइक्लोब्यूटानिल का छिड़काव करें।",
        "prevention": "Prune vines for canopy aeration and destroy all mummified grapes."
    },
    "Grape___Esca_(Black_Measles)": {
        "crop_name": "Grape",
        "crop_hindi": "अंगूर",
        "disease_name": "Esca (Black Measles)",
        "disease_hindi": "एस्का रोग",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "'Tiger stripe' interveinal chlorosis and necrosis on leaves, small dark spots on berry skin.",
        "symptoms_hindi": "पत्तियों पर बाघ की धारियों जैसा पीलापन और सूखापन, फलों पर काले धब्बे।",
        "treatment": "Prune infected trunks down to healthy wood; apply wound sealants after winter pruning.",
        "treatment_hindi": "संक्रमित टहनियों को काटकर घावों पर फफूंदनाशक पेस्ट लगाएं।",
        "prevention": "Avoid pruning during rainy weather, disinfect pruning shears."
    },
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
        "crop_name": "Grape",
        "crop_hindi": "अंगूर",
        "disease_name": "Leaf Blight",
        "disease_hindi": "पत्ती झुलसा रोग",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Irregular dark brown patches on leaves with dark borders.",
        "symptoms_hindi": "पत्तियों पर अनियमित गहरे भूरे रंग के धब्बे।",
        "treatment": "Foliar spray with Copper Oxychloride or Carbendazim.",
        "treatment_hindi": "कॉपर ऑक्सीक्लोराइड या कार्बेन्डाजिम का छिड़काव करें।",
        "prevention": "Good vine canopy training and drainage."
    },
    "Grape___healthy": {
        "crop_name": "Grape",
        "crop_hindi": "अंगूर",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Uniform broad green leaves, spotless clusters.",
        "symptoms_hindi": "पत्तियां और गुच्छे पूरी तरह स्वस्थ हैं।",
        "treatment": "Maintain vine training and micro-nutrient foliar spray.",
        "treatment_hindi": "संतुलित सूक्ष्म पोषक तत्वों का छिड़काव जारी रखें।",
        "prevention": "Periodic surveillance and clean canopy architecture."
    },
    "Pepper,_bell___Bacterial_spot": {
        "crop_name": "Bell Pepper",
        "crop_hindi": "शिमला मिर्च",
        "disease_name": "Bacterial Spot",
        "disease_hindi": "जीवाणु धब्बा रोग",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Small, water-soaked, blister-like spots on leaves turning brown with yellow haloes.",
        "symptoms_hindi": "पत्तियों पर छोटे पानीदार दानेदार धब्बे जो भूरे हो जाते हैं।",
        "treatment": "Spray Copper hydroxide combined with Streptocycline.",
        "treatment_hindi": "कॉपर सल्फेट व स्ट्रेप्टोसाइक्लिन का छिड़काव करें।",
        "prevention": "Use hot water treated seeds, avoid field work when foliage is wet."
    },
    "Pepper,_bell___healthy": {
        "crop_name": "Bell Pepper",
        "crop_hindi": "शिमला मिर्च",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Smooth vibrant leaves and uniform fruit setting.",
        "symptoms_hindi": "पत्तियां चमकदार हरी और फल स्वस्थ हैं।",
        "treatment": "Standard calcium and boron foliar maintenance.",
        "treatment_hindi": "नियमित पोषण प्रबंधन।",
        "prevention": "Mulching and drip fertigation."
    },
    "Orange___Haunglongbing_(Citrus_greening)": {
        "crop_name": "Orange / Citrus",
        "crop_hindi": "संतरा / नींबू वर्गीय",
        "disease_name": "Citrus Greening (HLB)",
        "disease_hindi": "सिट्रस ग्रीनिंग (HLB)",
        "severity": "Severe",
        "is_healthy": False,
        "symptoms": "Asymmetrical blotchy mottle on leaves, yellow shoots, bitter misshapen green-ended fruit.",
        "symptoms_hindi": "पत्तियों पर धब्बेदार पीलापन, फलों का टेढ़ा-मेढ़ा और कड़वा होना।",
        "treatment": "No cure. Control citrus psyllid vector with Imidacloprid. Remove heavily diseased trees.",
        "treatment_hindi": "सिट्रस साइला कीट को नियंत्रित करने के लिए इमिडाक्लोप्रिड छिड़कें। गंभीर रूप से बीमार पेड़ों को हटाएं।",
        "prevention": "Plant disease-free certified nursery stock and use systemic insecticides for vector control."
    },
    "Peach___Bacterial_spot": {
        "crop_name": "Peach",
        "crop_hindi": "आड़ू",
        "disease_name": "Bacterial Spot",
        "disease_hindi": "जीवाणु धब्बा",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Small angular water-soaked lesions that drop out leaving a 'shot-hole' appearance.",
        "symptoms_hindi": "पत्तियों पर छोटे छिद्र जैसे धब्बे (शॉट-होल असर)।",
        "treatment": "Spray oxytetracycline or copper sprays at dormant and petal fall stages.",
        "treatment_hindi": "कॉपर फफूंदनाशक का छिड़काव करें।",
        "prevention": "Plant resistant peach cultivars and provide windbreaks."
    },
    "Peach___healthy": {
        "crop_name": "Peach",
        "crop_hindi": "आड़ू",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Smooth lanceolate leaves with deep green shine.",
        "symptoms_hindi": "पत्तियां पूरी तरह स्वस्थ हैं।",
        "treatment": "Standard pruning and fruit thinning.",
        "treatment_hindi": "नियमित कटाई-छंटाई और सिंचाई।",
        "prevention": "Routine orchard hygiene."
    },
    "Squash___Powdery_mildew": {
        "crop_name": "Squash / Pumpkin",
        "crop_hindi": "कद्दू / तोरई",
        "disease_name": "Powdery Mildew",
        "disease_hindi": "सफेद चूर्णी फफूंद (पाउडरी मिल्ड्यू)",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "White talcum powder-like fungal patches on leaf surfaces, causing early senescence.",
        "symptoms_hindi": "पत्तियों पर सफेद पाउडर जैसी फफूंद जमना, पत्तियों का सूखना।",
        "treatment": "Spray Wettable Sulfur (2g/L) or Dinocap or bio-fungicide like Potassium bicarbonate.",
        "treatment_hindi": "घुलनशील गंधक (सल्फर 2 ग्राम/लीटर) या पोटैशियम बाइकार्बोनेट का छिड़काव करें।",
        "prevention": "Ensure wide plant spacing for sunlight, avoid excessive shade."
    },
    "Strawberry___Leaf_scorch": {
        "crop_name": "Strawberry",
        "crop_hindi": "स्ट्रॉबेरी",
        "disease_name": "Leaf Scorch",
        "disease_hindi": "पत्ती झुलस रोग",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "Purplish to reddish-brown irregular blotches on leaves that enlarge and dry up tissue.",
        "symptoms_hindi": "पत्तियों पर बैंगनी-लाल धब्बे जो बाद में जलने जैसे दिखते हैं।",
        "treatment": "Apply Captan or Myclobutanil at crown emergence and after harvest renovation.",
        "treatment_hindi": "कैप्टन या माइक्लोब्यूटानिल का छिड़काव करें।",
        "prevention": "Mow and clear old foliage after harvest, avoid sprinkler irrigation."
    },
    "Strawberry___healthy": {
        "crop_name": "Strawberry",
        "crop_hindi": "स्ट्रॉबेरी",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Lush trifoliate green foliage and bright white flowers.",
        "symptoms_hindi": "पत्तियां और फूल पूरी तरह निरोग हैं।",
        "treatment": "Maintain straw mulch and drip watering.",
        "treatment_hindi": "मल्चिंग और ड्रिप सिंचाई जारी रखें।",
        "prevention": "Keep fruit off direct contact with damp soil."
    },
    "Cherry_(including_sour)___Powdery_mildew": {
        "crop_name": "Cherry",
        "crop_hindi": "चेरी",
        "disease_name": "Powdery Mildew",
        "disease_hindi": "पाउडरी मिल्ड्यू",
        "severity": "Moderate",
        "is_healthy": False,
        "symptoms": "White powdery fungal growth on young leaves and twigs, leaf curling and distorted shoot tips.",
        "symptoms_hindi": "कोमल पत्तियों पर सफेद चूर्ण, पत्तियों का मुड़ना।",
        "treatment": "Apply sulfur or Myclobutanil at petal fall.",
        "treatment_hindi": "सल्फर फफूंदनाशक का छिड़काव करें।",
        "prevention": "Prune for open tree center, optimize airflow."
    },
    "Cherry_(including_sour)___healthy": {
        "crop_name": "Cherry",
        "crop_hindi": "चेरी",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Clean serrated deep-green foliage without powdery coating.",
        "symptoms_hindi": "पत्तियां पूरी तरह स्वस्थ हैं।",
        "treatment": "Standard orchard maintenance.",
        "treatment_hindi": "नियमित पोषण।",
        "prevention": "Dormant season spray schedule."
    },
    "Blueberry___healthy": {
        "crop_name": "Blueberry",
        "crop_hindi": "ब्लूबेरी",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Healthy oval waxy green leaves.",
        "symptoms_hindi": "पत्तियां स्वस्थ हैं।",
        "treatment": "Maintain soil acidity (pH 4.5-5.2) and pine bark mulch.",
        "treatment_hindi": "अम्लीय मिट्टी और मल्चिंग बनाए रखें।",
        "prevention": "Acidic fertigation and good drainage."
    },
    "Raspberry___healthy": {
        "crop_name": "Raspberry",
        "crop_hindi": "रसभरी",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Vibrant pinnate green leaves, sturdy cane growth.",
        "symptoms_hindi": "पत्तियां स्वस्थ हैं।",
        "treatment": "Trellising and seasonal cane thinning.",
        "treatment_hindi": "तारों पर सहारा दें।",
        "prevention": "Airflow between rows."
    },
    "Soybean___healthy": {
        "crop_name": "Soybean",
        "crop_hindi": "सोयाबीन",
        "disease_name": "Healthy Plant",
        "disease_hindi": "स्वस्थ पौधा",
        "severity": "None",
        "is_healthy": True,
        "symptoms": "Uniform deep green trifoliate foliage without rust pustules or yellow mottling.",
        "symptoms_hindi": "पत्तियां पूरी तरह हरी और स्वस्थ हैं।",
        "treatment": "Ensure adequate Rhizobium inoculation and balanced potash.",
        "treatment_hindi": "संतुलित पोटाश और राइजोबियम उपचार।",
        "prevention": "Crop rotation with wheat or gram."
    }
}

def get_disease_info(class_id: str) -> Dict[str, Any]:
    """Retrieve disease info by class id with safe defaults."""
    if class_id in DISEASE_METADATA:
        data = dict(DISEASE_METADATA[class_id])
        data["class_id"] = class_id
        return data
    
    # Generic fallback if not explicitly defined
    parts = class_id.split("___")
    crop = parts[0].replace("_", " ")
    disease = parts[1].replace("_", " ") if len(parts) > 1 else "Unknown"
    is_healthy = "healthy" in disease.lower()
    
    return {
        "class_id": class_id,
        "crop_name": crop,
        "crop_hindi": crop,
        "disease_name": disease,
        "disease_hindi": disease,
        "severity": "None" if is_healthy else "Moderate",
        "is_healthy": is_healthy,
        "symptoms": "Healthy leaf tissue." if is_healthy else f"Symptoms typical of {disease} on {crop}.",
        "symptoms_hindi": "स्वस्थ पौधा।" if is_healthy else f"{crop} पर {disease} के सामान्य लक्षण।",
        "treatment": "No treatment required." if is_healthy else "Apply recommended broad-spectrum fungicide or bactericide.",
        "treatment_hindi": "उपचार की आवश्यकता नहीं।" if is_healthy else "कृषि विशेषज्ञ की सलाह अनुसार फफूंदनाशक का छिड़काव करें।",
        "prevention": "Continue regular field hygiene and crop scouting."
    }
