package com.fasaldrishti.app.ui.localization

import androidx.compose.runtime.compositionLocalOf
import com.fasaldrishti.app.data.local.AppLanguage

data class Strings(
    // Bottom Navigation
    val navHome: String,
    val navDoctor: String,
    val navScan: String,
    val navHistory: String,
    val navProfile: String,

    // Home Screen
    val homeGreeting: String,
    val homeSubtitle: String,
    val homeWeatherTitle: String,
    val homeQuickScanTitle: String,
    val homeQuickScanSubtitle: String,
    val homeScanNowButton: String,
    val homeRecentScansTitle: String,
    val homeViewAll: String,
    val homeNoScansYet: String,
    val homeLibraryTitle: String,
    val homeLibrarySubtitle: String,

    // Scan & Camera Screen
    val scanOpticalSensor: String,
    val scanInstruction: String,
    val scanTakePhoto: String,
    val scanFromGallery: String,
    val scanKeepLeafClear: String,

    // Result & Diagnosis Dossier
    val resultDossierTitle: String,
    val resultConfidence: String,
    val resultSeverity: String,
    val resultSymptoms: String,
    val resultOrganicSolution: String,
    val resultChemicalTreatment: String,
    val resultPreventionTips: String,
    val resultRescan: String,
    val resultConsultAiDoctor: String,
    val resultShare: String,

    // AI Doctor / Chat Screen
    val chatTitle: String,
    val chatSubtitle: String,
    val chatTypePlaceholder: String,
    val chatWelcomeMessage: String,
    val chatClearHistoryTitle: String,
    val chatClearHistoryConfirm: String,
    val chatClearHistoryButton: String,
    val chatCancelButton: String,

    // Profile Screen
    val profileTitle: String,
    val profileScansCount: String,
    val profileAccuracy: String,
    val profileSettingsTitle: String,
    val profileCropLibraryTitle: String,
    val profileClearChatTitle: String,
    val profileClearScansTitle: String,
    val profileAboutTitle: String,
    val profileLogout: String,

    // Settings Screen
    val settingsTitle: String,
    val settingsThemeTitle: String,
    val settingsThemeLight: String,
    val settingsThemeDark: String,
    val settingsThemeSystem: String,
    val settingsLanguageTitle: String,
    val settingsLanguageSubtitle: String,
    val settingsChooseLanguage: String,
    val settingsSoftwareUpdates: String,
    val settingsUpToDate: String,
    val settingsUpdateAvailable: String,
    val settingsAiEngineTitle: String,
    val settingsNnapiAccelerator: String,
    val settings120HzLock: String,
    val settingsNotificationsTitle: String,
    val settingsSprayAlerts: String,
    val settingsAgronomyTips: String,

    // General
    val backButton: String,
    val closeButton: String,
    val applyButton: String
)

val EnglishStrings = Strings(
    navHome = "Home",
    navDoctor = "AI Salah",
    navScan = "Scan",
    navHistory = "History",
    navProfile = "Profile",

    homeGreeting = "Namaste",
    homeSubtitle = "AI Precision Agronomy & Crop Vision",
    homeWeatherTitle = "Agri-Weather & Spray Advisory",
    homeQuickScanTitle = "Diagnose Crop Disease",
    homeQuickScanSubtitle = "Point camera at leaf for instant AI prescription",
    homeScanNowButton = "Scan Crop Now",
    homeRecentScansTitle = "Recent Field Scans",
    homeViewAll = "View All",
    homeNoScansYet = "No crop scans recorded yet",
    homeLibraryTitle = "Crop Pathology Library",
    homeLibrarySubtitle = "Explore 40+ crop diseases & treatments",

    scanOpticalSensor = "AI OPTICAL SENSOR",
    scanInstruction = "Align leaf within target boundary",
    scanTakePhoto = "Capture Leaf Photo",
    scanFromGallery = "Upload from Gallery",
    scanKeepLeafClear = "Ensure good lighting and focus on the disease spot",

    resultDossierTitle = "Diagnosis Dossier",
    resultConfidence = "Confidence",
    resultSeverity = "Severity",
    resultSymptoms = "Identified Symptoms",
    resultOrganicSolution = "Organic & Biological Cure",
    resultChemicalTreatment = "Chemical Prescription",
    resultPreventionTips = "Preventive Agronomy Advice",
    resultRescan = "Rescan",
    resultConsultAiDoctor = "Consult AI Salah",
    resultShare = "Share Result",

    chatTitle = "Fasal Drishti AI Salah",
    chatSubtitle = "Multimodal Agronomist • Gemini & NVIDIA NIM",
    chatTypePlaceholder = "Ask question in any language...",
    chatWelcomeMessage = "Namaste! I am your AI Agronomist Salahkar. Ask me anything about crop diseases, sprays, fertilizers, or soil care.",
    chatClearHistoryTitle = "Clear AI Chat History?",
    chatClearHistoryConfirm = "Are you sure you want to permanently delete your on-device AI chat conversation?",
    chatClearHistoryButton = "Clear Chat",
    chatCancelButton = "Cancel",

    profileTitle = "Profile",
    profileScansCount = "Total Scans",
    profileAccuracy = "AI Accuracy",
    profileSettingsTitle = "Settings & Preferences",
    profileCropLibraryTitle = "Crop Pathology Library",
    profileClearChatTitle = "Clear AI Chat History",
    profileClearScansTitle = "Clear Field Scan History",
    profileAboutTitle = "About Fasal Drishti",
    profileLogout = "Log Out",

    settingsTitle = "Settings & Preferences",
    settingsThemeTitle = "Theme & Appearance",
    settingsThemeLight = "Light",
    settingsThemeDark = "Dark",
    settingsThemeSystem = "System",
    settingsLanguageTitle = "App Language",
    settingsLanguageSubtitle = "Select your preferred Indian language",
    settingsChooseLanguage = "Choose App Language",
    settingsSoftwareUpdates = "Software Updates",
    settingsUpToDate = "Fasal Drishti is up to date",
    settingsUpdateAvailable = "New update available",
    settingsAiEngineTitle = "AI Engine & Diagnostics",
    settingsNnapiAccelerator = "NNAPI Neural Accelerator",
    settings120HzLock = "120Hz Fluid UI Lock",
    settingsNotificationsTitle = "Notifications & Reminders",
    settingsSprayAlerts = "Spray & Crop Health Alerts",
    settingsAgronomyTips = "Agronomy Tips & Tricks",

    backButton = "Back",
    closeButton = "Close",
    applyButton = "Apply"
)

val HindiStrings = Strings(
    navHome = "होम",
    navDoctor = "AI सलाह",
    navScan = "स्कैन",
    navHistory = "इतिहास",
    navProfile = "प्रोफ़ाइल",

    homeGreeting = "नमस्ते",
    homeSubtitle = "AI फसल सुरक्षा एवं रोग निदान",
    homeWeatherTitle = "कृषि-मौसम एवं स्प्रे सलाह",
    homeQuickScanTitle = "फसल रोग की जांच करें",
    homeQuickScanSubtitle = "पत्ती की फोटो लें और तुरंत AI इलाज पाएं",
    homeScanNowButton = "फसल स्कैन करें",
    homeRecentScansTitle = "हाल के फसल स्कैन",
    homeViewAll = "सभी देखें",
    homeNoScansYet = "अभी तक कोई स्कैन रिकॉर्ड नहीं है",
    homeLibraryTitle = "फसल रोग ज्ञानकोष",
    homeLibrarySubtitle = "40+ फसलों के रोग और उनके उपचार जानें",

    scanOpticalSensor = "AI ऑप्टिकल सेंसर",
    scanInstruction = "पत्ती को कैमरे के बीच में रखें",
    scanTakePhoto = "पत्ती की फोटो लें",
    scanFromGallery = "गैलरी से अपलोड करें",
    scanKeepLeafClear = "अच्छी रोशनी में रोग वाले भाग पर फोकस करें",

    resultDossierTitle = "रोग निदान रिपोर्ट",
    resultConfidence = "सटीकता",
    resultSeverity = "गंभीरता",
    resultSymptoms = "पहचाने गए लक्षण",
    resultOrganicSolution = "जैविक एवं प्राकृतिक उपचार",
    resultChemicalTreatment = "रासायनिक स्प्रे एवं दवा",
    resultPreventionTips = "फसल रोकथाम सलाह",
    resultRescan = "पुनः स्कैन",
    resultConsultAiDoctor = "AI सलाह लें",
    resultShare = "रिपोर्ट शेयर करें",

    chatTitle = "फसल दृष्टि AI सलाह",
    chatSubtitle = "कृषि विशेषज्ञ AI • Gemini एवं NVIDIA NIM",
    chatTypePlaceholder = "अपनी भाषा में कोई भी सवाल पूछें...",
    chatWelcomeMessage = "नमस्ते! मैं आपका AI फसल सलाहकार हूँ। फसल रोग, दवा, खाद या कीटनाशक के बारे में कुछ भी पूछें।",
    chatClearHistoryTitle = "चैट इतिहास मिटाएं?",
    chatClearHistoryConfirm = "क्या आप अपने फोन से पूरी AI चैट हिस्ट्री हटाना चाहते हैं?",
    chatClearHistoryButton = "चैट हटाएं",
    chatCancelButton = "रद्द करें",

    profileTitle = "प्रोफ़ाइल",
    profileScansCount = "कुल स्कैन",
    profileAccuracy = "AI सटीकता",
    profileSettingsTitle = "सेटिंग्स एवं प्राथमिकताएँ",
    profileCropLibraryTitle = "फसल रोग ज्ञानकोष",
    profileClearChatTitle = "AI चैट इतिहास साफ़ करें",
    profileClearScansTitle = "स्कैन इतिहास साफ़ करें",
    profileAboutTitle = "फसल दृष्टि के बारे में",
    profileLogout = "लॉग आउट",

    settingsTitle = "सेटिंग्स एवं प्राथमिकताएँ",
    settingsThemeTitle = "थीम एवं रूप-रंग",
    settingsThemeLight = "लाइट",
    settingsThemeDark = "डार्क",
    settingsThemeSystem = "सिस्टम",
    settingsLanguageTitle = "ऐप की भाषा",
    settingsLanguageSubtitle = "अपनी पसंदीदा भारतीय भाषा चुनें",
    settingsChooseLanguage = "ऐप भाषा चुनें",
    settingsSoftwareUpdates = "सॉफ़्टवेयर अपडेट",
    settingsUpToDate = "फसल दृष्टि अप-टू-डेट है",
    settingsUpdateAvailable = "नया अपडेट उपलब्ध है",
    settingsAiEngineTitle = "AI इंजन एवं डायग्नोस्टिक्स",
    settingsNnapiAccelerator = "NNAPI न्यूरल एक्सेलेरेटर",
    settings120HzLock = "120Hz स्मूथ यूआई",
    settingsNotificationsTitle = "सूचनाएं एवं रिमाइंडर",
    settingsSprayAlerts = "स्प्रे एवं फसल स्वास्थ्य अलर्ट",
    settingsAgronomyTips = "कृषि टिप्स एवं सुझाव",

    backButton = "पीछे",
    closeButton = "बंद करें",
    applyButton = "लागू करें"
)

val BengaliStrings = Strings(
    navHome = "হোম",
    navDoctor = "AI পরামর্শ",
    navScan = "স্ক্যান",
    navHistory = "ইতিহাস",
    navProfile = "প্রোফাইল",

    homeGreeting = "নমস্কার",
    homeSubtitle = "AI নির্ভুল কৃষি ও ফসল সুরক্ষা",
    homeWeatherTitle = "আবহাওয়া ও স্প্রে পরামর্শ",
    homeQuickScanTitle = "ফসলের রোগ নির্ণয় করুন",
    homeQuickScanSubtitle = "পাতার ছবি তুলুন এবং তাৎক্ষণিক AI প্রতিকার পান",
    homeScanNowButton = "ফসল স্ক্যান করুন",
    homeRecentScansTitle = "সাম্প্রতিক স্ক্যান",
    homeViewAll = "সব দেখুন",
    homeNoScansYet = "এখনও কোনো স্ক্যান নেই",
    homeLibraryTitle = "ফসল রোগ জ্ঞানকোষ",
    homeLibrarySubtitle = "৪০+ ফসলের রোগ ও চিকিৎসা জানুন",

    scanOpticalSensor = "AI অপটিক্যাল সেন্সর",
    scanInstruction = "পাতাকে ক্যামেরার মাঝে রাখুন",
    scanTakePhoto = "পাতার ছবি তুলুন",
    scanFromGallery = "গ্যালারি থেকে নিন",
    scanKeepLeafClear = "পর্যাপ্ত আলোয় রোগের অংশে ফোকাস করুন",

    resultDossierTitle = "রোগ নির্ণয় রিপোর্ট",
    resultConfidence = "নির্ভুলতা",
    resultSeverity = "তীব্রতা",
    resultSymptoms = "চিহ্নিত লক্ষণ",
    resultOrganicSolution = "জৈব ও প্রাকৃতিক প্রতিকার",
    resultChemicalTreatment = "রাসায়নিক ওষুধ ও স্প্রে",
    resultPreventionTips = "প্রতিরোধমূলক পরামর্শ",
    resultRescan = "পুনরায় স্ক্যান",
    resultConsultAiDoctor = "AI পরামর্শ নিন",
    resultShare = "শেয়ার করুন",

    chatTitle = "ফসল দৃষ্টি AI পরামর্শ",
    chatSubtitle = "কৃষি বিশেষজ্ঞ AI • Gemini ও NVIDIA",
    chatTypePlaceholder = "আপনার ভাষায় প্রশ্ন লিখুন...",
    chatWelcomeMessage = "নমস্কার! আমি আপনার AI কৃষি পরামর্শদাতা। ফসলের রোগ, সার বা কীটনাশক সম্পর্কে যেকোনো প্রশ্ন করুন।",
    chatClearHistoryTitle = "চ্যাট হিস্ট্রি মুছবেন?",
    chatClearHistoryConfirm = "আপনি কি ফোনে সংরক্ষিত AI চ্যাট মুছে ফেলতে চান?",
    chatClearHistoryButton = "মুছে ফেলুন",
    chatCancelButton = "বাতিল",

    profileTitle = "প্রোফাইল",
    profileScansCount = "মোট স্ক্যান",
    profileAccuracy = "AI নির্ভুলতা",
    profileSettingsTitle = "সেটিংস ও পছন্দসমূহ",
    profileCropLibraryTitle = "ফসল রোগ লাইব্রেরি",
    profileClearChatTitle = "AI চ্যাট হিস্ট্রি মুছুন",
    profileClearScansTitle = "স্ক্যান হিস্ট্রি মুছুন",
    profileAboutTitle = "ফসল দৃষ্টি সম্পর্কে",
    profileLogout = "লগ আউট",

    settingsTitle = "সেটিংস ও পছন্দসমূহ",
    settingsThemeTitle = "থিম ও ডিসপ্লে",
    settingsThemeLight = "লাইট",
    settingsThemeDark = "ডার্ক",
    settingsThemeSystem = "সিস্টেম",
    settingsLanguageTitle = "অ্যাপের ভাষা",
    settingsLanguageSubtitle = "আপনার পছন্দের ভারতীয় ভাষা নির্বাচন করুন",
    settingsChooseLanguage = "অ্যাপের ভাষা বাছুন",
    settingsSoftwareUpdates = "সফটওয়্যার আপডেট",
    settingsUpToDate = "ফসল দৃষ্টি সম্পূর্ণ আপ-টু-ডেট",
    settingsUpdateAvailable = "নতুন আপডেট উপলব্ধ",
    settingsAiEngineTitle = "AI ইঞ্জিন ও গতি",
    settingsNnapiAccelerator = "NNAPI নিউরাল অ্যাক্সিলারেটর",
    settings120HzLock = "১২০Hz মসৃণ ডিসপ্লে",
    settingsNotificationsTitle = "বিজ্ঞপ্তি ও অনুস্মারক",
    settingsSprayAlerts = "স্প্রে ও ফসলের স্বাস্থ্য সতর্কতা",
    settingsAgronomyTips = "কৃষি টিপস ও পরামর্শ",

    backButton = "পেছনে",
    closeButton = "বন্ধ",
    applyButton = "প্রয়োগ করুন"
)

val PunjabiStrings = Strings(
    navHome = "ਮੁੱਖ ਪੰਨਾ",
    navDoctor = "AI ਸਲਾਹ",
    navScan = "ਸਕੈਨ",
    navHistory = "ਇਤਿਹਾਸ",
    navProfile = "ਪ੍ਰੋਫਾਈਲ",

    homeGreeting = "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
    homeSubtitle = "AI ਫਸਲ ਸੁਰੱਖਿਆ ਅਤੇ ਰੋਗ ਜਾਂਚ",
    homeWeatherTitle = "ਮੌਸਮ ਅਤੇ ਸਪਰੇਅ ਸਲਾਹ",
    homeQuickScanTitle = "ਫਸਲ ਦੇ ਰੋਗ ਦੀ ਜਾਂਚ ਕਰੋ",
    homeQuickScanSubtitle = "ਪੱਤੇ ਦੀ ਫੋਟੋ ਲਓ ਅਤੇ ਤੁਰੰਤ ਇਲਾਜ ਪਾਓ",
    homeScanNowButton = "ਫਸਲ ਸਕੈਨ ਕਰੋ",
    homeRecentScansTitle = "ਹਾਲੀਆ ਸਕੈਨ",
    homeViewAll = "ਸਾਰੇ ਵੇਖੋ",
    homeNoScansYet = "ਅਜੇ ਕੋਈ ਸਕੈਨ ਦਰਜ ਨਹੀਂ ਹੈ",
    homeLibraryTitle = "ਫਸਲ ਰੋਗ ਲਾਇਬ੍ਰੇਰੀ",
    homeLibrarySubtitle = "40+ ਫਸਲਾਂ ਦੇ ਰੋਗ ਅਤੇ ਉਪਾਅ ਜਾਣੋ",

    scanOpticalSensor = "AI ਆਪਟੀਕਲ ਸੈਂਸਰ",
    scanInstruction = "ਪੱਤੇ ਨੂੰ ਕੈਮਰੇ ਦੇ ਵਿਚਕਾਰ ਰੱਖੋ",
    scanTakePhoto = "ਪੱਤੇ ਦੀ ਫੋਟੋ ਲਓ",
    scanFromGallery = "ਗੈਲਰੀ ਤੋਂ ਚੁਣੋ",
    scanKeepLeafClear = "ਰੋਸ਼ਨੀ ਵਿੱਚ ਰੋਗ ਵਾਲੇ ਹਿੱਸੇ 'ਤੇ ਫੋਕਸ ਕਰੋ",

    resultDossierTitle = "ਰੋਗ ਜਾਂਚ ਰਿਪੋਰਟ",
    resultConfidence = "ਸ਼ੁੱਧਤਾ",
    resultSeverity = "ਗੰਭੀਰਤਾ",
    resultSymptoms = "ਪਛਾਣੇ ਗਏ ਲੱਛਣ",
    resultOrganicSolution = "ਜੈਵਿਕ ਅਤੇ ਕੁਦਰਤੀ ਉਪਾਅ",
    resultChemicalTreatment = "ਕੈਮੀਕਲ ਸਪਰੇਅ ਅਤੇ ਦਵਾਈ",
    resultPreventionTips = "ਰੋਕਥਾਮ ਸਲਾਹ",
    resultRescan = "ਮੁੜ ਸਕੈਨ ਕਰੋ",
    resultConsultAiDoctor = "AI ਸਲਾਹ ਲਵੋ",
    resultShare = "ਸਾਂਝਾ ਕਰੋ",

    chatTitle = "ਫਸਲ ਦ੍ਰਿਸ਼ਟੀ AI ਸਲਾਹ",
    chatSubtitle = "ਖੇਤੀ ਮਾਹਰ AI • Gemini ਅਤੇ NVIDIA",
    chatTypePlaceholder = "ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਵਾਲ ਪੁੱਛੋ...",
    chatWelcomeMessage = "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਤੁਹਾਡਾ AI ਖੇਤੀ ਡਾਕਟਰ ਹਾਂ। ਫਸਲ ਦੀ ਬਿਮਾਰੀ ਜਾਂ ਖਾਦ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ।",
    chatClearHistoryTitle = "ਗੱਲਬਾਤ ਇਤਿਹਾਸ ਮਿਟਾਓ?",
    chatClearHistoryConfirm = "ਕੀ ਤੁਸੀਂ ਫੋਨ ਵਿੱਚੋਂ AI ਚੈਟ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    chatClearHistoryButton = "ਮਿਟਾਓ",
    chatCancelButton = "ਰੱਦ ਕਰੋ",

    profileTitle = "ਪ੍ਰੋਫਾਈਲ",
    profileScansCount = "ਕੁੱਲ ਸਕੈਨ",
    profileAccuracy = "AI ਸ਼ੁੱਧਤਾ",
    profileSettingsTitle = "ਸੈਟਿੰਗਾਂ",
    profileCropLibraryTitle = "ਫਸਲ ਰੋਗ ਲਾਇਬ੍ਰੇਰੀ",
    profileClearChatTitle = "AI ਚੈਟ ਇਤਿਹਾਸ ਸਾਫ਼ ਕਰੋ",
    profileClearScansTitle = "ਸਕੈਨ ਇਤਿਹਾਸ ਸਾਫ਼ ਕਰੋ",
    profileAboutTitle = "ਫਸਲ ਦ੍ਰਿਸ਼ਟੀ ਬਾਰੇ",
    profileLogout = "ਲਾਗ ਆਉਟ",

    settingsTitle = "ਸੈਟਿੰਗਾਂ",
    settingsThemeTitle = "ਥੀਮ",
    settingsThemeLight = "ਲਾਈਟ",
    settingsThemeDark = "ਡਾਰਕ",
    settingsThemeSystem = "ਸਿਸਟਮ",
    settingsLanguageTitle = "ਐਪ ਦੀ ਭਾਸ਼ਾ",
    settingsLanguageSubtitle = "ਆਪਣੀ ਮਨਪਸੰਦ ਭਾਰਤੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    settingsChooseLanguage = "ਭਾਸ਼ਾ ਚੁਣੋ",
    settingsSoftwareUpdates = "ਸਾਫਟਵੇਅਰ ਅੱਪਡੇਟ",
    settingsUpToDate = "ਫਸਲ ਦ੍ਰਿਸ਼ਟੀ ਅੱਪ-ਟੂ-ਡੇਟ ਹੈ",
    settingsUpdateAvailable = "ਨਵਾਂ ਅੱਪਡੇਟ ਉਪਲਬਧ ਹੈ",
    settingsAiEngineTitle = "AI ਇੰਜਣ",
    settingsNnapiAccelerator = "NNAPI ਐਕਸਲੇਰੇਟਰ",
    settings120HzLock = "120Hz ਸਮੂਥ ਡਿਸਪਲੇ",
    settingsNotificationsTitle = "ਸੂਚਨਾਵਾਂ",
    settingsSprayAlerts = "ਸਪਰੇਅ ਚੇਤਾਵਨੀਆਂ",
    settingsAgronomyTips = "ਖੇਤੀ ਸੁਝਾਅ",

    backButton = "ਪਿੱਛੇ",
    closeButton = "ਬੰਦ ਕਰੋ",
    applyButton = "ਲਾਗੂ ਕਰੋ"
)

val MarathiStrings = Strings(
    navHome = "मुख्यपृष्ठ",
    navDoctor = "AI सलाह",
    navScan = "स्कॅन",
    navHistory = "इतिहास",
    navProfile = "प्रोफाइल",

    homeGreeting = "नमस्कार",
    homeSubtitle = "AI अचूक कृषी व पीक संरक्षण",
    homeWeatherTitle = "कृषी-हवामान व फवारणी सल्ला",
    homeQuickScanTitle = "पीक रोगाचे निदान करा",
    homeQuickScanSubtitle = "पानाचा फोटो घ्या आणि त्वरित AI उपचार मिळवा",
    homeScanNowButton = "पीक स्कॅन करा",
    homeRecentScansTitle = "अलीकडील स्कॅन",
    homeViewAll = "सर्व पहा",
    homeNoScansYet = "अद्याप कोणतेही स्कॅन नाही",
    homeLibraryTitle = "पीक रोग ज्ञानकोश",
    homeLibrarySubtitle = "४०+ पिकांचे रोग आणि उपाय जाणून घ्या",

    scanOpticalSensor = "AI ऑप्टिकल सेन्सर",
    scanInstruction = "पान कॅमेऱ्याच्या मध्यभागी ठेवा",
    scanTakePhoto = "पानाचा फोटो काढा",
    scanFromGallery = "गॅलरीतून निवडा",
    scanKeepLeafClear = "चांगल्या प्रकाशात रोगाच्या भागावर फोकस करा",

    resultDossierTitle = "रोग निदान अहवाल",
    resultConfidence = "अचूकता",
    resultSeverity = "तीव्रता",
    resultSymptoms = "ओळखलेली लक्षणे",
    resultOrganicSolution = "सेंद्रिय व नैसर्गिक उपाय",
    resultChemicalTreatment = "रासायनिक फवारणी व औषधे",
    resultPreventionTips = "प्रतिबंधात्मक सल्ला",
    resultRescan = "पुन्हा स्कॅन करा",
    resultConsultAiDoctor = "AI सल्ला घ्या",
    resultShare = "शेअर करा",

    chatTitle = "फसल दृष्टी AI सल्ला",
    chatSubtitle = "कृषी तज्ज्ञ AI • Gemini आणि NVIDIA",
    chatTypePlaceholder = "तुमच्या भाषेत कोणताही प्रश्न विचारा...",
    chatWelcomeMessage = "नमस्कार! मी तुमचा AI पीक सल्लागार आहे. पिकांचे रोग, खते किंवा कीटकनाशकांविषयी काहीही विचारा।",
    chatClearHistoryTitle = "चॅट इतिहास हटवायचा?",
    chatClearHistoryConfirm = "तुम्ही फोनमधील AI चॅट इतिहास कायमचा हटवू इच्छिता?",
    chatClearHistoryButton = "हटवा",
    chatCancelButton = "रद्द करा",

    profileTitle = "प्रोफाइल",
    profileScansCount = "एकूण स्कॅन",
    profileAccuracy = "AI अचूकता",
    profileSettingsTitle = "सेटिंग्ज आणि प्राधान्ये",
    profileCropLibraryTitle = "पीक रोग ज्ञानकोश",
    profileClearChatTitle = "AI चॅट इतिहास साफ करा",
    profileClearScansTitle = "स्कॅन इतिहास साफ करा",
    profileAboutTitle = "फसल दृष्टी बद्दल",
    profileLogout = "लॉग आउट",

    settingsTitle = "सेटिंग्ज आणि प्राधान्ये",
    settingsThemeTitle = "थीम आणि डिस्प्ले",
    settingsThemeLight = "लाइट",
    settingsThemeDark = "डार्क",
    settingsThemeSystem = "सिस्टम",
    settingsLanguageTitle = "अ‍ॅपची भाषा",
    settingsLanguageSubtitle = "तुमची आवडती भारतीय भाषा निवडा",
    settingsChooseLanguage = "अ‍ॅप भाषा निवडा",
    settingsSoftwareUpdates = "सॉफ्टवेअर अपडेट्स",
    settingsUpToDate = "फसल दृष्टी अद्ययावत आहे",
    settingsUpdateAvailable = "नवीन अपडेट उपलब्ध आहे",
    settingsAiEngineTitle = "AI इंजिन आणि गती",
    settingsNnapiAccelerator = "NNAPI न्यूरल प्रवेगक",
    settings120HzLock = "१२०Hz स्मूथ यूआय",
    settingsNotificationsTitle = "सूचना आणि स्मरणपत्रे",
    settingsSprayAlerts = "फवारणी व पीक आरोग्य सूचना",
    settingsAgronomyTips = "कृषी सल्ला आणि टिप्स",

    backButton = "मागे",
    closeButton = "बंद करा",
    applyButton = "लागू करा"
)

val TeluguStrings = Strings(
    navHome = "హోమ్",
    navDoctor = "AI సలహా",
    navScan = "స్కాన్",
    navHistory = "చరిత్ర",
    navProfile = "ప్రొఫైల్",

    homeGreeting = "నమస్కారం",
    homeSubtitle = "AI పంట సంరక్షణ & తెగుళ్ల నిర్ధారణ",
    homeWeatherTitle = "వ్యవసాయ వాతావరణం & పిచికారీ సలహా",
    homeQuickScanTitle = "పంట తెగులును గుర్తించండి",
    homeQuickScanSubtitle = "ఆకు ఫోటో తీసి తక్షణమే AI చికిత్స పొందండి",
    homeScanNowButton = "ఇప్పుడే స్కాన్ చేయండి",
    homeRecentScansTitle = "ఇటీవలి స్కాన్లు",
    homeViewAll = "అన్నీ చూడండి",
    homeNoScansYet = "ఇంకా ఎలాంటి స్కాన్లు నమోదు కాలేదు",
    homeLibraryTitle = "పంట తెగుళ్ల సమాచార కేంద్రం",
    homeLibrarySubtitle = "40+ పంటల తెగుళ్లు & నివారణ పద్ధతులు",

    scanOpticalSensor = "AI ఆప్టికల్ సెన్సార్",
    scanInstruction = "ఆకును కెమెరా మధ్యలో ఉంచండి",
    scanTakePhoto = "ఆకు ఫోటో తీయండి",
    scanFromGallery = "గ్యాలరీ నుండి ఎంచుకోండి",
    scanKeepLeafClear = "మంచి వెలుతురులో తెగులు ఉన్న భాగంపై ఫోకస్ చేయండి",

    resultDossierTitle = "తెగులు నిర్ధారణ నివేదిక",
    resultConfidence = "ఖచ్చితత్వం",
    resultSeverity = "తీవ్రత",
    resultSymptoms = "గుర్తించిన లక్షణాలు",
    resultOrganicSolution = "సేంద్రీయ & సహజ నివారణ",
    resultChemicalTreatment = "రసాయన మందులు & పిచికారీ",
    resultPreventionTips = "నివారణ సూచనలు",
    resultRescan = "మళ్లీ స్కాన్ చేయండి",
    resultConsultAiDoctor = "AI సలహా పొందండి",
    resultShare = "షేర్ చేయండి",

    chatTitle = "ఫసల్ దృష్టి AI సలహా",
    chatSubtitle = "వ్యవసాయ నిపుణుడు AI • Gemini & NVIDIA",
    chatTypePlaceholder = "మీ భాషలో ఏదైనా ప్రశ్న అడగండి...",
    chatWelcomeMessage = "నమస్కారం! నేను మీ AI పంటల సలహాదారుని. పంటల తెగుళ్లు, ఎరువులు లేదా పురుగుమందుల గురించి ఏదైనా అడగండి.",
    chatClearHistoryTitle = "చాట్ చరిత్రను తొలగించాలా?",
    chatClearHistoryConfirm = "మీరు మీ ఫోన్ నుండి AI చాట్ చరిత్రను తొలగించాలనుకుంటున్నారా?",
    chatClearHistoryButton = "తొలగించు",
    chatCancelButton = "రద్దు చేయి",

    profileTitle = "ప్రొఫైల్",
    profileScansCount = "మొత్తం స్కాన్లు",
    profileAccuracy = "AI ఖచ్చితత్వం",
    profileSettingsTitle = "సెట్టింగ్‌లు & ప్రాధాన్యతలు",
    profileCropLibraryTitle = "పంట తెగుళ్ల లైబ్రరీ",
    profileClearChatTitle = "AI చాట్ చరిత్రను క్లియర్ చేయండి",
    profileClearScansTitle = "స్కాన్ చరిత్రను క్లియర్ చేయండి",
    profileAboutTitle = "ఫసల్ దృష్టి గురించి",
    profileLogout = "లాగ్ అవుట్",

    settingsTitle = "సెట్టింగ్‌లు & ప్రాధాన్యతలు",
    settingsThemeTitle = "థీమ్ & రూపం",
    settingsThemeLight = "లైట్",
    settingsThemeDark = "డార్క్",
    settingsThemeSystem = "సిస్టమ్",
    settingsLanguageTitle = "యాప్ భాష",
    settingsLanguageSubtitle = "మీకు నచ్చిన భారతీయ భాషను ఎంచుకోండి",
    settingsChooseLanguage = "భాషను ఎంచుకోండి",
    settingsSoftwareUpdates = "సాఫ్ట్‌వేర్ అప్‌డేట్‌లు",
    settingsUpToDate = "ఫసల్ దృష్టి అప్‌డేట్ చేయబడింది",
    settingsUpdateAvailable = "కొత్త అప్‌డేట్ అందుబాటులో ఉంది",
    settingsAiEngineTitle = "AI ఇంజిన్",
    settingsNnapiAccelerator = "NNAPI న్యూరల్ యాక్సిలరేటర్",
    settings120HzLock = "120Hz స్మూత్ డిస్‌ప్లే",
    settingsNotificationsTitle = "నోటిఫికేషన్‌లు",
    settingsSprayAlerts = "పిచికారీ హెచ్చరికలు",
    settingsAgronomyTips = "వ్యవసాయ చిట్కాలు",

    backButton = "వెనుకకు",
    closeButton = "మూసివేయి",
    applyButton = "వర్తించు"
)

val TamilStrings = Strings(
    navHome = "முகப்பு",
    navDoctor = "AI ஆலோசனை",
    navScan = "ஸ்கேன்",
    navHistory = "வரலாறு",
    navProfile = "சுயவிவரம்",

    homeGreeting = "வணக்கம்",
    homeSubtitle = "AI துல்லிய வேளாண்மை & பயிர் பாதுகாப்பு",
    homeWeatherTitle = "வானிலை & தெளிப்பு ஆலோசனை",
    homeQuickScanTitle = "பயிர் நோயைக் கண்டறியவும்",
    homeQuickScanSubtitle = "இலையை புகைப்படம் எடுத்து உடனடி AI சிகிச்சை பெறவும்",
    homeScanNowButton = "பயிரை ஸ்கேன் செய்யவும்",
    homeRecentScansTitle = "சமீபத்திய ஸ்கேன்கள்",
    homeViewAll = "அனைத்தும்",
    homeNoScansYet = "இதுவரை ஸ்கேன்கள் எதுவும் இல்லை",
    homeLibraryTitle = "பயிர் நோய் நூலகம்",
    homeLibrarySubtitle = "40+ பயிர் நோய்கள் மற்றும் சிகிச்சைகள்",

    scanOpticalSensor = "AI ஆப்டிகல் சென்சார்",
    scanInstruction = "இலையை கேமராவின் நடுவில் வைக்கவும்",
    scanTakePhoto = "புகைப்படம் எடுக்கவும்",
    scanFromGallery = "கேலரியிலிருந்து தேர்வு செய்க",
    scanKeepLeafClear = "நல்ல வெளிச்சத்தில் பாதிக்கப்பட்ட பகுதியில் கவனம் செலுத்துங்கள்",

    resultDossierTitle = "நோய் கண்டறிதல் அறிக்கை",
    resultConfidence = "துல்லியம்",
    resultSeverity = "தீவிரம்",
    resultSymptoms = "கண்டறியப்பட்ட அறிகுறிகள்",
    resultOrganicSolution = "இயற்கை மற்றும் உயிரியல் தீர்வு",
    resultChemicalTreatment = "இரசாயன மருந்து மற்றும் தெளிப்பு",
    resultPreventionTips = "தடுப்பு ஆலோசனைகள்",
    resultRescan = "மீண்டும் ஸ்கேன் செய்",
    resultConsultAiDoctor = "AI ஆலோசனை பெறுக",
    resultShare = "பகிர்",

    chatTitle = "பசல் திருஷ்டி AI ஆலோசனை",
    chatSubtitle = "வேளாண் நிபுணர் AI • Gemini & NVIDIA",
    chatTypePlaceholder = "உங்கள் மொழியில் கேள்விகளைக் கேளுங்கள்...",
    chatWelcomeMessage = "வணக்கம்! நான் உங்கள் AI வேளாண் ஆலோசகர். பயிர் நோய்கள், உரங்கள் பற்றி எது வேண்டுமானாலும் கேளுங்கள்.",
    chatClearHistoryTitle = "அரட்டை வரலாற்றை நீக்கவா?",
    chatClearHistoryConfirm = "போனில் உள்ள AI அரட்டை வரலாற்றை அழிக்க விரும்புகிறீர்களா?",
    chatClearHistoryButton = "அழி",
    chatCancelButton = "ரத்து",

    profileTitle = "சுயவிவரம்",
    profileScansCount = "மொத்த ஸ்கேன்கள்",
    profileAccuracy = "AI துல்லியம்",
    profileSettingsTitle = "அமைப்புகள் & விருப்பங்கள்",
    profileCropLibraryTitle = "பயிர் நோய் நூலகம்",
    profileClearChatTitle = "AI அரட்டை வரலாற்றை அழிக்கவும்",
    profileClearScansTitle = "ஸ்கேன் வரலாற்றை அழிக்கவும்",
    profileAboutTitle = "பசல் திருஷ்டி பற்றி",
    profileLogout = "வெளியேறு",

    settingsTitle = "அமைப்புகள் & விருப்பங்கள்",
    settingsThemeTitle = "தீம் & தோற்றம்",
    settingsThemeLight = "லைட்",
    settingsThemeDark = "டார்க்",
    settingsThemeSystem = "சிஸ்டம்",
    settingsLanguageTitle = "செயலி மொழி",
    settingsLanguageSubtitle = "உங்கள் விருப்பமான இந்திய மொழியைத் தேர்வுசெய்க",
    settingsChooseLanguage = "மொழியைத் தேர்வுசெய்",
    settingsSoftwareUpdates = "மென்பொருள் புதுப்பிப்புகள்",
    settingsUpToDate = "பசல் திருஷ்டி புதுப்பித்த நிலையில் உள்ளது",
    settingsUpdateAvailable = "புதிய புதுப்பிப்பு உள்ளது",
    settingsAiEngineTitle = "AI என்ஜின்",
    settingsNnapiAccelerator = "NNAPI நியூரல் முடுக்கி",
    settings120HzLock = "120Hz மென்மையான திரை",
    settingsNotificationsTitle = "அறிவிப்புகள்",
    settingsSprayAlerts = "மருந்து தெளிப்பு எச்சரிக்கைகள்",
    settingsAgronomyTips = "வேளாண் குறிப்புகள்",

    backButton = "பின்செல்",
    closeButton = "மூடு",
    applyButton = "பயன்படுத்து"
)

val GujaratiStrings = Strings(
    navHome = "હોમ",
    navDoctor = "AI સલાહ",
    navScan = "સ્કૅન",
    navHistory = "ઇતિહાસ",
    navProfile = "પ્રોફાઇલ",

    homeGreeting = "નમસ્તે",
    homeSubtitle = "AI પાક સંરક્ષણ અને રોગ નિદાન",
    homeWeatherTitle = "કૃષિ-હવામાન અને છંટકાવ સલાહ",
    homeQuickScanTitle = "પાકના રોગની તપાસ કરો",
    homeQuickScanSubtitle = "પાંદડાનો ફોટો લો અને તરત AI ઉપચાર મેળવો",
    homeScanNowButton = "પાક સ્કૅન કરો",
    homeRecentScansTitle = "તાજેતરના સ્કૅન",
    homeViewAll = "બધા જુઓ",
    homeNoScansYet = "હજી કોઈ સ્કૅન નોંધાયેલ નથી",
    homeLibraryTitle = "પાક રોગ જ્ઞાનકોશ",
    homeLibrarySubtitle = "૪૦+ પાકોના રોગ અને ઉપાય જાણો",

    scanOpticalSensor = "AI ઑપ્ટિકલ સેન્સર",
    scanInstruction = "પાંદડાને કૅમેરાની વચ્ચે રાખો",
    scanTakePhoto = "પાંદડાનો ફોટો લો",
    scanFromGallery = "ગૅલેરીમાંથી પસંદ કરો",
    scanKeepLeafClear = "સારા પ્રકાશમાં રોગવાળા ભાગ પર ફોકસ કરો",

    resultDossierTitle = "રોગ નિદાન અહેવાલ",
    resultConfidence = "ચોકસાઈ",
    resultSeverity = "તીવ્રતા",
    resultSymptoms = "ઓળખાયેલા લક્ષણો",
    resultOrganicSolution = "જૈવિક અને કુદરતી ઉપાય",
    resultChemicalTreatment = "રાસાયણિક દવા અને છંટકાવ",
    resultPreventionTips = "અટકાવવાના પગલાં",
    resultRescan = "ફરી સ્કૅન કરો",
    resultConsultAiDoctor = "AI સલાહ લો",
    resultShare = "શેર કરો",

    chatTitle = "ફસલ દ્રષ્ટિ AI સલાહ",
    chatSubtitle = "કૃષિ નિષ્ણાત AI • Gemini અને NVIDIA",
    chatTypePlaceholder = "તમારી ભાષામાં કોઈ પણ પ્રશ્ન પૂછો...",
    chatWelcomeMessage = "નમસ્તે! હું તમારો AI પાક સલાહકાર છું. પાકના રોગ, ખાતર કે દવા વિશે કંઈ પણ પૂછો.",
    chatClearHistoryTitle = "ચૅટ ઇતિહાસ સાફ કરવો?",
    chatClearHistoryConfirm = "શું તમે ફોનમાંથી AI ચૅટ ઇતિહાસ કાયમ માટે કાઢી નાખવા માંગો છો?",
    chatClearHistoryButton = "સાફ કરો",
    chatCancelButton = "રદ કરો",

    profileTitle = "પ્રોફાઇલ",
    profileScansCount = "કુલ સ્કૅન",
    profileAccuracy = "AI ચોકસાઈ",
    profileSettingsTitle = "સેટિંગ્સ અને પસંદગીઓ",
    profileCropLibraryTitle = "પાક રોગ લાઇબ્રેરી",
    profileClearChatTitle = "AI ચૅટ ઇતિહાસ સાફ કરો",
    profileClearScansTitle = "સ્કૅન ઇતિહાસ સાફ કરો",
    profileAboutTitle = "ફસલ દ્રષ્ટિ વિશે",
    profileLogout = "લૉગ આઉટ",

    settingsTitle = "સેટિંગ્સ અને પસંદગીઓ",
    settingsThemeTitle = "થીમ અને દેખાવ",
    settingsThemeLight = "લાઇટ",
    settingsThemeDark = "ડાર્ક",
    settingsThemeSystem = "સિસ્ટમ",
    settingsLanguageTitle = "ઍપની ભાષા",
    settingsLanguageSubtitle = "તમારી પસંદગીની ભારતીય ભાષા પસંદ કરો",
    settingsChooseLanguage = "ઍપ ભાષા પસંદ કરો",
    settingsSoftwareUpdates = "સૉફ્ટવેર અપડેટ્સ",
    settingsUpToDate = "ફસલ દ્રષ્ટિ અપ-ટૂ-ડેટ છે",
    settingsUpdateAvailable = "નવું અપડેટ ઉપલબ્ધ છે",
    settingsAiEngineTitle = "AI એન્જિન",
    settingsNnapiAccelerator = "NNAPI ન્યુરલ એક્સિલરેટર",
    settings120HzLock = "120Hz સ્મૂથ ડિસ્પ્લે",
    settingsNotificationsTitle = "સૂચનાઓ",
    settingsSprayAlerts = "છંટકાવની ચેતવણીઓ",
    settingsAgronomyTips = "કૃષિ ટિપ્સ",

    backButton = "પાછા",
    closeButton = "બંધ કરો",
    applyButton = "લાગુ કરો"
)

val KannadaStrings = Strings(
    navHome = "ಮುಖಪುಟ",
    navDoctor = "AI ಸಲಹೆ",
    navScan = "ಸ್ಕ್ಯಾನ್",
    navHistory = "ಇತಿಹಾಸ",
    navProfile = "ಪ್ರೊಫೈಲ್",

    homeGreeting = "ನಮಸ್ಕಾರ",
    homeSubtitle = "AI ಬೆಳೆ ಸಂರಕ್ಷಣೆ ಮತ್ತು ರೋಗ ನಿರ್ಣಯ",
    homeWeatherTitle = "ಕೃಷಿ ಹವಾಮಾನ ಮತ್ತು ಸಿಂಪರಣೆ ಸಲಹೆ",
    homeQuickScanTitle = "ಬೆಳೆ ರೋಗ ಪರೀಕ್ಷಿಸಿ",
    homeQuickScanSubtitle = "ಎಲೆಯ ಫೋಟೋ ತೆಗೆದು ತಕ್ಷಣ AI ಚಿಕಿತ್ಸೆ ಪಡೆಯಿರಿ",
    homeScanNowButton = "ಈಗಲೇ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    homeRecentScansTitle = "ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು",
    homeViewAll = "ಎಲ್ಲವನ್ನೂ ನೋಡಿ",
    homeNoScansYet = "ಇನ್ನೂ ಯಾವುದೇ ಸ್ಕ್ಯಾನ್ ದಾಖಲಾಗಿಲ್ಲ",
    homeLibraryTitle = "ಬೆಳೆ ರೋಗ ಮಾಹಿತಿ ಕೋಶ",
    homeLibrarySubtitle = "40+ ಬೆಳೆಗಳ ರೋಗಗಳು ಮತ್ತು ಚಿಕಿತ್ಸೆಗಳು",

    scanOpticalSensor = "AI ಆಪ್ಟಿಕಲ್ ಸೆನ್ಸಾರ್",
    scanInstruction = "ಎಲೆಯನ್ನು ಕ್ಯಾಮೆರಾದ ಮಧ್ಯದಲ್ಲಿ ಇರಿಸಿ",
    scanTakePhoto = "ಎಲೆಯ ಫೋಟೋ ತೆಗೆಯಿರಿ",
    scanFromGallery = "ಗ್ಯಾಲರಿಯಿಂದ ಆರಿಸಿ",
    scanKeepLeafClear = "ಉತ್ತಮ ಬೆಳಕಿನಲ್ಲಿ ರೋಗವಿರುವ ಭಾಗದ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸಿ",

    resultDossierTitle = "ರೋಗ ನಿರ್ಣಯ ವರದಿ",
    resultConfidence = "ನಿಖರತೆ",
    resultSeverity = "ತೀವ್ರತೆ",
    resultSymptoms = "ಗುರುತಿಸಲಾದ ಲಕ್ಷಣಗಳು",
    resultOrganicSolution = "ಸಾವಯವ ಮತ್ತು ನೈಸರ್ಗಿಕ ಚಿಕಿತ್ಸೆ",
    resultChemicalTreatment = "ರಾಸಾಯನಿಕ ಔಷಧಿ ಮತ್ತು ಸಿಂಪರಣೆ",
    resultPreventionTips = "ಮುನ್ನೆಚ್ಚರಿಕೆ ಸಲಹೆಗಳು",
    resultRescan = "ಮರು ಸ್ಕ್ಯಾನ್",
    resultConsultAiDoctor = "AI ಸಲಹೆ ಪಡೆಯಿರಿ",
    resultShare = "ಹಂಚಿಕೊಳ್ಳಿ",

    chatTitle = "ಫಸಲ್ ದೃಷ್ಟಿ AI ಸಲಹೆ",
    chatSubtitle = "ಕೃಷಿ ತಜ್ಞ AI • Gemini & NVIDIA",
    chatTypePlaceholder = "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಯಾವುದೇ ಪ್ರಶ್ನೆ ಕೇಳಿ...",
    chatWelcomeMessage = "ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ AI ಬೆಳೆ ಸಲಹೆಗಾರ. ಬೆಳೆ ರೋಗ, ರಸಗೊಬ್ಬರ ಅಥವಾ ಕೀಟನಾಶಕಗಳ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ.",
    chatClearHistoryTitle = "ಸಂಭಾಷಣೆ ಇತಿಹಾಸ ಅಳಿಸಬೇಕೆ?",
    chatClearHistoryConfirm = "ನಿಮ್ಮ ಫೋನ್‌ನಿಂದ AI ಚಾಟ್ ಇತಿಹಾಸವನ್ನು ಅಳಿಸಲು ನೀವು ಬಯಸುವಿರಾ?",
    chatClearHistoryButton = "ಅಳಿಸಿ",
    chatCancelButton = "ರದ್ದುಮಾಡಿ",

    profileTitle = "ಪ್ರೊಫೈಲ್",
    profileScansCount = "ಒಟ್ಟು ಸ್ಕ್ಯಾನ್‌ಗಳು",
    profileAccuracy = "AI ನಿಖರತೆ",
    profileSettingsTitle = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಆದ್ಯತೆಗಳು",
    profileCropLibraryTitle = "ಬೆಳೆ ರೋಗ ಲೈಬ್ರರಿ",
    profileClearChatTitle = "AI ಚಾಟ್ ಇತಿಹಾಸ ತೆರವುಗೊಳಿಸಿ",
    profileClearScansTitle = "ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ ತೆರವುಗೊಳಿಸಿ",
    profileAboutTitle = "ಫಸಲ್ ದೃಷ್ಟಿ ಬಗ್ಗೆ",
    profileLogout = "ಲಾಗ್ ಔಟ್",

    settingsTitle = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಆದ್ಯತೆಗಳು",
    settingsThemeTitle = "ಥೀಮ್ ಮತ್ತು ಪ್ರದರ್ಶನ",
    settingsThemeLight = "ಲೈಟ್",
    settingsThemeDark = "ಡಾರ್ಕ್",
    settingsThemeSystem = "ಸಿಸ್ಟಮ್",
    settingsLanguageTitle = "ಆ್ಯಪ್ ಭಾಷೆ",
    settingsLanguageSubtitle = "ನಿಮ್ಮ ಮೆಚ್ಚಿನ ಭಾರತೀಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    settingsChooseLanguage = "ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    settingsSoftwareUpdates = "ಸಾಫ್ಟ್‌ವೇರ್ ಅಪ್‌ಡೇಟ್‌ಗಳು",
    settingsUpToDate = "ಫಸಲ್ ದೃಷ್ಟಿ ನವೀಕೃತವಾಗಿದೆ",
    settingsUpdateAvailable = "ಹೊಸ ನವೀಕರಣ ಲಭ್ಯವಿದೆ",
    settingsAiEngineTitle = "AI ಎಂಜಿನ್",
    settingsNnapiAccelerator = "NNAPI ನ್ಯೂರಲ್ ವೇಗವರ್ಧಕ",
    settings120HzLock = "120Hz ಸ್ಮೂತ್ ಪ್ರದರ್ಶನ",
    settingsNotificationsTitle = "ಅಧಿಸೂಚನೆಗಳು",
    settingsSprayAlerts = "ಸಿಂಪರಣೆ ಎಚ್ಚರಿಕೆಗಳು",
    settingsAgronomyTips = "ಕೃಷಿ ಸಲಹೆಗಳು",

    backButton = "ಹಿಂದೆ",
    closeButton = "ಮುಚ್ಚಿ",
    applyButton = "ಅನ್ವಯಿಸು"
)

val OdiaStrings = Strings(
    navHome = "ମୁଖ୍ୟପୃଷ୍ଠା",
    navDoctor = "AI ପରାମର୍ଶ",
    navScan = "ସ୍କାନ୍",
    navHistory = "ଇତିହାସ",
    navProfile = "ପ୍ରୋଫାଇଲ୍",

    homeGreeting = "ନମସ୍କାର",
    homeSubtitle = "AI ଫସଲ ସୁରକ୍ଷା ଓ ରୋଗ ନିଦାନ",
    homeWeatherTitle = "କୃଷି-ପାଣିପାଗ ଓ ସ୍ପ୍ରେ ପରାମର୍ଶ",
    homeQuickScanTitle = "ଫସଲ ରୋଗ ଚିହ୍ନଟ କରନ୍ତୁ",
    homeQuickScanSubtitle = "ପତ୍ରର ଫଟୋ ଉଠାନ୍ତୁ ଏବଂ ତୁରନ୍ତ AI ଚିକିତ୍ସା ପାଆନ୍ତୁ",
    homeScanNowButton = "ଫସଲ ସ୍କାନ୍ କରନ୍ତୁ",
    homeRecentScansTitle = "ସାମ୍ପ୍ରତିକ ସ୍କାନ୍",
    homeViewAll = "ସବୁ ଦେଖନ୍ତୁ",
    homeNoScansYet = "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ସ୍କାନ୍ ରେକର୍ଡ ନାହିଁ",
    homeLibraryTitle = "ଫସଲ ରୋଗ ଜ୍ଞାନକୋଷ",
    homeLibrarySubtitle = "୪୦+ ଫସଲର ରୋଗ ଏବଂ ଉପଚାର ଜାଣନ୍ତୁ",

    scanOpticalSensor = "AI ଅପ୍ଟିକାଲ୍ ସେନ୍ସର",
    scanInstruction = "ପତ୍ରକୁ କ୍ୟାମେରାର ମଝିରେ ରଖନ୍ତୁ",
    scanTakePhoto = "ପତ୍ରର ଫଟୋ ଉଠାନ୍ତୁ",
    scanFromGallery = "ଗ୍ୟାଲେରୀରୁ ବାଛନ୍ତୁ",
    scanKeepLeafClear = "ଭଲ ଆଲୋକରେ ରୋଗାକ୍ରାନ୍ତ ଅଂଶ ଉପରେ ଫୋକସ୍ କରନ୍ତୁ",

    resultDossierTitle = "ରୋଗ ନିଦାନ ରିପୋର୍ଟ",
    resultConfidence = "ସଠିକତା",
    resultSeverity = "ତୀବ୍ରତା",
    resultSymptoms = "ଚିହ୍ନଟ ଲକ୍ଷଣ",
    resultOrganicSolution = "ଜୈବିକ ଓ ପ୍ରାକୃତିକ ଉପଚାର",
    resultChemicalTreatment = "ରାସାୟନିକ ଔଷଧ ଓ ସ୍ପ୍ରେ",
    resultPreventionTips = "ପ୍ରତିରୋଧକ ପରାମର୍ଶ",
    resultRescan = "ପୁନଃ ସ୍କାନ୍",
    resultConsultAiDoctor = "AI ପରାମର୍ଶ ନିଅନ୍ତୁ",
    resultShare = "ସେୟାର୍ କରନ୍ତୁ",

    chatTitle = "ଫସଲ ଦୃଷ୍ଟି AI ପରାମର୍ଶ",
    chatSubtitle = "କୃଷି ବିଶେଷଜ୍ଞ AI • Gemini ଓ NVIDIA",
    chatTypePlaceholder = "ଆପଣଙ୍କ ଭାଷାରେ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ...",
    chatWelcomeMessage = "ନମସ୍କାର! ମୁଁ ଆପଣଙ୍କ AI କୃଷି ପରାମର୍ଶଦାତା। ଫସଲ ରୋଗ, ଖତ ବା କୀଟନାଶକ ବିଷୟରେ ଯାହା ବି ପଚାରନ୍ତୁ।",
    chatClearHistoryTitle = "ଚାଟ୍ ଇତିହାସ ଲିଭାଇବେ?",
    chatClearHistoryConfirm = "ଆପଣ ଫୋନରୁ AI ଚାଟ୍ ଇତିହାସ ହଟାଇବାକୁ ଚାହାଁନ୍ତି କି?",
    chatClearHistoryButton = "ଲିଭାନ୍ତୁ",
    chatCancelButton = "ବାତିଲ",

    profileTitle = "ପ୍ରୋଫାଇଲ୍",
    profileScansCount = "ମୋଟ ସ୍କାନ୍",
    profileAccuracy = "AI ସଠିକତା",
    profileSettingsTitle = "ସେଟିଂସ୍ ଓ ପସନ୍ଦ",
    profileCropLibraryTitle = "ଫସଲ ରୋଗ ଲାଇବ୍ରେରୀ",
    profileClearChatTitle = "AI ଚାଟ୍ ଇତିହାସ ସଫା କରନ୍ତୁ",
    profileClearScansTitle = "ସ୍କାନ୍ ଇତିହାସ ସଫା କରନ୍ତୁ",
    profileAboutTitle = "ଫସଲ ଦୃଷ୍ଟି ବିଷୟରେ",
    profileLogout = "ଲଗ୍ ଆଉଟ୍",

    settingsTitle = "ସେଟିଂସ୍ ଓ ପସନ୍ଦ",
    settingsThemeTitle = "ଥିମ୍ ଓ ରୂପରେଖ",
    settingsThemeLight = "ଲାଇଟ୍",
    settingsThemeDark = "ଡାର୍କ",
    settingsThemeSystem = "ସିଷ୍ଟମ୍",
    settingsLanguageTitle = "ଆପ୍ ଭାଷା",
    settingsLanguageSubtitle = "ଆପଣଙ୍କ ପସନ୍ଦର ଭାରତୀୟ ଭାଷା ବାଛନ୍ତୁ",
    settingsChooseLanguage = "ଭାଷା ବାଛନ୍ତୁ",
    settingsSoftwareUpdates = "ସଫ୍ଟୱେର୍ ଅପଡେଟ୍",
    settingsUpToDate = "ଫସଲ ଦୃଷ୍ଟି ଅପ-ଟୁ-ଡେଟ୍ ଅଛି",
    settingsUpdateAvailable = "ନୂଆ ଅପଡେଟ୍ ଉପଲବ୍ଧ",
    settingsAiEngineTitle = "AI ଇଞ୍ଜିନ୍",
    settingsNnapiAccelerator = "NNAPI ନ୍ୟୁରାଲ୍ ଏକ୍ସିଲରେଟର",
    settings120HzLock = "୧୨୦Hz ସ୍ମୁଥ୍ ପ୍ରଦର୍ଶନ",
    settingsNotificationsTitle = "ବିଜ୍ଞପ୍ତି",
    settingsSprayAlerts = "ସ୍ପ୍ରେ ଚେତାବନୀ",
    settingsAgronomyTips = "କୃଷି ପରାମର୍ଶ",

    backButton = "ପଛକୁ",
    closeButton = "ବନ୍ଦ",
    applyButton = "ଲାଗୁ କରନ୍ତୁ"
)

fun getAppStrings(language: AppLanguage): Strings {
    return when (language) {
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.HINDI -> HindiStrings
        AppLanguage.BENGALI -> BengaliStrings
        AppLanguage.PUNJABI -> PunjabiStrings
        AppLanguage.MARATHI -> MarathiStrings
        AppLanguage.TELUGU -> TeluguStrings
        AppLanguage.TAMIL -> TamilStrings
        AppLanguage.GUJARATI -> GujaratiStrings
        AppLanguage.KANNADA -> KannadaStrings
        AppLanguage.ODIA -> OdiaStrings
    }
}

val LocalAppStrings = compositionLocalOf { EnglishStrings }
